# Generated by Django 6.0.2 on 2026-02-19 02:01

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du partenaire')),
                ('type', models.CharField(blank=True, max_length=100, verbose_name='Type (ONG, Entreprise, etc.)')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif')], default='ACTIF', max_length=10, verbose_name='Statut')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_debut', models.DateField(verbose_name='Date de début du partenariat')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('TRESORIER', 'Trésorier'), ('CHARGE_PROJET', 'Chargé de Projet'), ('MEMBRE', 'Membre / Bénévole')], default='MEMBRE', max_length=20, verbose_name='Rôle')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='profils/', verbose_name='Photo de profil')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'action")),
                ('type', models.CharField(choices=[('SENSIBILISATION', 'Sensibilisation'), ('EDUCATION', 'Éducation'), ('ACCOMPAGNEMENT', 'Accompagnement'), ('SOLIDARITE', 'Action Solidaire'), ('FORMATION', 'Formation'), ('AUTRE', 'Autre')], default='SENSIBILISATION', max_length=20, verbose_name="Type d'action")),
                ('description', models.TextField(verbose_name='Description')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_cloture', models.DateField(blank=True, null=True, verbose_name='Date de clôture')),
                ('lieu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lieu')),
                ('budget_prevu', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Budget prévu (FCFA)')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('PLANIFIEE', 'Planifiée'), ('CLOTUREE', 'Clôturée'), ('ANNULEE', 'Annulée')], default='PLANIFIEE', max_length=15, verbose_name='Statut')),
                ('nb_participants', models.PositiveIntegerField(default=0, verbose_name='Nombre de participants')),
                ('compte_rendu', models.TextField(blank=True, null=True, verbose_name='Compte rendu')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('partenaires', models.ManyToManyField(blank=True, related_name='actions_soutenues', to='core.partenaire', verbose_name='Partenaires')),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='DemandeAdhesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('motivation', models.TextField(verbose_name='Motivation / Message')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=15, verbose_name='Statut')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
            ],
            options={
                'verbose_name': "Demande d'adhésion",
                'verbose_name_plural': "Demandes d'adhésion",
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant (FCFA)')),
                ('date_depense', models.DateField(verbose_name='Date de la dépense')),
                ('categorie', models.CharField(choices=[('COMMUNICATION', 'Communication'), ('LOCATION', 'Location de salle'), ('INTERVENANT', 'Rémunération intervenant'), ('MATERIEL', 'Matériel pédagogique'), ('TRANSPORT', 'Transport'), ('RESTAURATION', 'Restauration'), ('ADMINISTRATIF', 'Frais administratifs'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=15, verbose_name='Statut')),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='depenses/justificatifs/', verbose_name='Justificatif (PDF/Image)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses', to='core.action', verbose_name='Action associée')),
                ('saisi_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_saisies', to=settings.AUTH_USER_MODEL, verbose_name='Saisi par')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date_depense'],
            },
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('date_adhesion', models.DateField(verbose_name="Date d'adhésion")),
                ('type_membre', models.CharField(choices=[('PRESIDENT', 'Président'), ('VICE_PRESIDENT', 'Vice-Président'), ('SECRETAIRE', 'Secrétaire'), ('TRESORIER', 'Trésorier'), ('BENEVOLE', 'Bénévole'), ('MEMBRE_ACTIF', 'Membre Actif')], default='BENEVOLE', max_length=20, verbose_name='Type')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('EN_ATTENTE', 'En attente de validation')], default='EN_ATTENTE', max_length=15, verbose_name='Statut')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profil_membre', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur')),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Don',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant (FCFA)')),
                ('date_don', models.DateField(verbose_name='Date du don')),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('VIREMENT', 'Virement bancaire'), ('MOBILE_MONEY', 'Mobile Money'), ('CHEQUE', 'Chèque'), ('EN_LIGNE', 'Paiement en ligne'), ('AUTRE', 'Autre')], default='ESPECES', max_length=20, verbose_name='Mode de paiement')),
                ('anonyme', models.BooleanField(default=False, verbose_name='Don anonyme')),
                ('nom_donateur_externe', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom du donateur (externe)')),
                ('recu_genere', models.BooleanField(default=False, verbose_name='Reçu généré')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dons', to='core.action', verbose_name='Action financée')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dons_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
                ('donateur_membre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dons', to='core.membre', verbose_name='Donateur (membre)')),
                ('donateur_partenaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dons_effectues', to='core.partenaire', verbose_name='Partenaire donateur')),
            ],
            options={
                'verbose_name': 'Don',
                'verbose_name_plural': 'Dons',
                'ordering': ['-date_don'],
            },
        ),
        migrations.CreateModel(
            name='PhotoAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='actions/photos/', verbose_name='Photo')),
                ('legende', models.CharField(blank=True, max_length=200, null=True, verbose_name='Légende')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.action', verbose_name='Action')),
            ],
            options={
                'verbose_name': "Photo d'action",
                'verbose_name_plural': "Photos d'actions",
            },
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant (FCFA)')),
                ('date_paiement', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('statut', models.CharField(choices=[('PAYEE', 'Payée'), ('IMPAYEE', 'Impayée'), ('EN_ATTENTE', 'En attente')], default='EN_ATTENTE', max_length=15, verbose_name='Statut')),
                ('periodicite', models.CharField(choices=[('MENSUELLE', 'Mensuelle'), ('TRIMESTRIELLE', 'Trimestrielle'), ('ANNUELLE', 'Annuelle')], default='ANNUELLE', max_length=15, verbose_name='Périodicité')),
                ('periode_concernee', models.CharField(help_text='Ex: 2024, T1-2024, Janvier 2024', max_length=50, verbose_name='Période concernée')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotisations_enregistrees', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='core.membre', verbose_name='Membre')),
            ],
            options={
                'verbose_name': 'Cotisation',
                'verbose_name_plural': 'Cotisations',
                'ordering': ['-date_paiement'],
                'unique_together': {('membre', 'periode_concernee', 'periodicite')},
            },
        ),
    ]
