# Generated by Django 6.0.2 on 2026-02-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='membre',
            name='sexe',
            field=models.CharField(blank=True, choices=[('HOMME', 'Homme'), ('FEMME', 'Femme'), ('AUTRE', 'Autre / Non précisé')], max_length=10, null=True, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='type_membre',
            field=models.CharField(choices=[('PRESIDENT', 'Président'), ('VICE_PRESIDENT', 'Vice-Président'), ('SECRETAIRE', 'Secrétaire'), ('TRESORIER', 'Trésorier'), ('RESPONSABLE_RH', 'Responsable RH'), ('RESPONSABLE_COM', 'Responsable Communication'), ('CHARGE_PROJET', 'Chargé de Projet'), ('CHARGE_PARTENARIAT', 'Chargé de Partenariat'), ('BENEVOLE', 'Bénévole'), ('MEMBRE_ACTIF', 'Membre Actif')], default='BENEVOLE', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('TRESORIER', 'Trésorier'), ('CHARGE_PROJET', 'Chargé de Projet'), ('RESPONSABLE_RH', 'Responsable RH'), ('CHARGE_PARTENARIAT', 'Chargé de Partenariat'), ('MEMBRE', 'Membre / Bénévole')], default='MEMBRE', max_length=20, verbose_name='Rôle'),
        ),
    ]
