# Generated by Django 6.0.2 on 2026-02-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaire',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='partenaires/logos/', verbose_name='Logo'),
        ),
    ]
