# Generated by Django 6.0.2 on 2026-03-01 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo_profil',
        ),
        migrations.AddField(
            model_name='membre',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='membres/photos/', verbose_name='Photo de profil'),
        ),
    ]
