# Generated by Django 6.0.2 on 2026-03-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='nb_participants_max',
            field=models.PositiveIntegerField(blank=True, help_text='Laisser vide pour des inscriptions illimitées.', null=True, verbose_name='Capacité maximale'),
        ),
        migrations.AlterField(
            model_name='action',
            name='nb_participants',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de participants (legacy/manuel)'),
        ),
    ]
