# Generated by Django 6.0.2 on 2026-03-06 06:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_action_nb_participants_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeadhesion',
            name='adresse',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='demandeadhesion',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='demandeadhesion',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='demandes/documents/', validators=[core.models.valider_document_adhesion], verbose_name='Document joint (CV, photo — JPG/PNG/PDF, max 5 Mo)'),
        ),
        migrations.AddField(
            model_name='demandeadhesion',
            name='domaine_expertise',
            field=models.CharField(blank=True, choices=[('SANTE_MENTALE', 'Santé mentale & psychologie'), ('SANTE_PHYSIQUE', 'Santé physique & sport'), ('EDUCATION', 'Éducation & pédagogie'), ('COMMUNICATION', 'Communication & médias'), ('TECHNOLOGIE', 'Technologie & numérique'), ('DROIT', 'Droit & plaidoyer'), ('FINANCE', 'Finance & gestion'), ('LOGISTIQUE', 'Logistique & coordination'), ('ART_CULTURE', 'Art & culture'), ('AUTRE', 'Autre')], max_length=20, null=True, verbose_name="Domaine d'expertise"),
        ),
        migrations.AddField(
            model_name='demandeadhesion',
            name='profil_linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='Profil LinkedIn'),
        ),
        migrations.AddField(
            model_name='demandeadhesion',
            name='type_membre_souhaite',
            field=models.CharField(choices=[('MEMBRE', 'Membre'), ('BENEVOLE', 'Bénévole'), ('PARTENAIRE', 'Partenaire')], default='MEMBRE', max_length=15, verbose_name='Type de membre souhaité'),
        ),
    ]
